name: auto_animated_example
description: Demonstrates how to use the auto_animated plugin.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_animated:
    path: ../

flutter:
  uses-material-design: true

